Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -68,7 +68,7 @@ jobs:
           name: docker image push
           command: |
             sudo docker images
-            docker tag $IMAGE_NAME $IMAGE_NAME:latest || { echo "retag failed"; exit 1; }
+            docker tag $IMAGE_NAME ghcr.io/$IMAGE_NAME:latest || { echo "retag failed"; exit 1; }
             docker push ghcr.io/$IMAGE_NAME:latest || { echo "push failed"; exit 1; }
             VERSION=$( docker images | grep -i $IMAGE_NAME | awk '{ print $2 }' | grep -i '^[0-9]' | sort | uniq )
             echo "Image version: $VERSION"
@@ -110,7 +110,7 @@ jobs:
           name: docker image push
           command: |
             docker images
-            docker tag $IMAGE_NAME $IMAGE_NAME:latest || { echo "retag failed"; exit 1; }
+            docker tag $IMAGE_NAME ghcr.io/$IMAGE_NAME:latest || { echo "retag failed"; exit 1; }
             docker push ghcr.io/$IMAGE_NAME:latest || { echo "push failed"; exit 1; }
             VERSION=$( docker images | grep -i $IMAGE_NAME | awk '{ print $2 }' | grep -i '^[0-9]' | sort | uniq )
             echo "Image version: $VERSION"
