Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -36,7 +36,7 @@ jobs:
     machine:
       image: ubuntu-2004:current
     environment:
-      IMAGE_NAME: "croc/unimus"
+      IMAGE_NAME: "accuris-infrastructure/unimus"
     steps:
       - checkout
       - attach_workspace:
@@ -44,8 +44,7 @@ jobs:
       - run:
           name: docker login
           command: |
-            echo $DOCKERHUB_PASS | docker login --username $DOCKERHUB_USER --password-stdin
-            echo $QUAYIO_PASS | docker login --username $QUAYIO_USER --password-stdin quay.io
+            echo $CR_PAT | sudo docker login ghcr.io -u accuris-infrastructure --password-stdin
       - run:
           name: docker build arm64
           command: |
@@ -64,26 +63,22 @@ jobs:
             echo "Unimus version: $UNIMUS_VERSION"
             [ -z "$UNIMUS_VERSION" ] && { echo "Unimus version not found"; exit 1; }
             # create version tag
-            docker tag $IMAGE_NAME $IMAGE_NAME:$UNIMUS_VERSION
-            docker tag $IMAGE_NAME quay.io/$IMAGE_NAME:$UNIMUS_VERSION
+            docker tag $IMAGE_NAME ghcr.io/$IMAGE_NAME:$UNIMUS_VERSION
       - run:
           name: docker image push
           command: |
-            docker images
+            sudo docker images
             docker tag $IMAGE_NAME $IMAGE_NAME:latest || { echo "retag failed"; exit 1; }
-            docker tag $IMAGE_NAME quay.io/$IMAGE_NAME:latest || { echo "retag failed"; exit 1; }
-            docker push $IMAGE_NAME:latest || { echo "push failed"; exit 1; }
-            docker push quay.io/$IMAGE_NAME:latest || { echo "push failed"; exit 1; }
+            docker push ghcr.io/$IMAGE_NAME:latest || { echo "push failed"; exit 1; }
             VERSION=$( docker images | grep -i $IMAGE_NAME | awk '{ print $2 }' | grep -i '^[0-9]' | sort | uniq )
             echo "Image version: $VERSION"
-            docker push $IMAGE_NAME:$VERSION || { echo "version ($VERSION) image push error"; exit 1; }
-            docker push quay.io/$IMAGE_NAME:$VERSION || { echo "version ($VERSION) image push error"; exit 1; }
+            docker push ghcr.io/$IMAGE_NAME:$VERSION || { echo "version ($VERSION) image push error"; exit 1; }
   containerbuilder-arm-job:
     machine:
       image: ubuntu-2004:current
     resource_class: arm.medium
     environment:
-      IMAGE_NAME: "croc/unimus-arm64"
+      IMAGE_NAME: "accuris-infrastructure/unimus-arm64"
     steps:
       - checkout
       - attach_workspace:
@@ -91,8 +86,7 @@ jobs:
       - run:
           name: docker login
           command: |
-            echo $DOCKERHUB_PASS | docker login --username $DOCKERHUB_USER --password-stdin
-            echo $QUAYIO_PASS | docker login --username $QUAYIO_USER --password-stdin quay.io
+            echo $CR_PAT | sudo docker login ghcr.io -u accuris-infrastructure --password-stdin
       - run:
           name: docker build arm64
           command: |
@@ -111,20 +105,16 @@ jobs:
             echo "Unimus version: $UNIMUS_VERSION"
             [ -z "$UNIMUS_VERSION" ] && { echo "Unimus version not found"; exit 1; }
             # create version tag
-            docker tag $IMAGE_NAME $IMAGE_NAME:$UNIMUS_VERSION
-            docker tag $IMAGE_NAME quay.io/$IMAGE_NAME:$UNIMUS_VERSION
+            docker tag $IMAGE_NAME ghcr.io/$IMAGE_NAME:$UNIMUS_VERSION
       - run:
           name: docker image push
           command: |
             docker images
             docker tag $IMAGE_NAME $IMAGE_NAME:latest || { echo "retag failed"; exit 1; }
-            docker tag $IMAGE_NAME quay.io/$IMAGE_NAME:latest || { echo "retag failed"; exit 1; }
-            docker push $IMAGE_NAME:latest || { echo "push failed"; exit 1; }
-            docker push quay.io/$IMAGE_NAME:latest || { echo "push failed"; exit 1; }
+            docker push ghcr.io/$IMAGE_NAME:latest || { echo "push failed"; exit 1; }
             VERSION=$( docker images | grep -i $IMAGE_NAME | awk '{ print $2 }' | grep -i '^[0-9]' | sort | uniq )
             echo "Image version: $VERSION"
-            docker push $IMAGE_NAME:$VERSION || { echo "version ($VERSION) image push error"; exit 1; }
-            docker push quay.io/$IMAGE_NAME:$VERSION || { echo "version ($VERSION) image push error"; exit 1; }
+            docker push ghcr.io/$IMAGE_NAME:$VERSION || { echo "version ($VERSION) image push error"; exit 1; }
 # workflows
 workflows:
   myflow:
