Fix

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -36,7 +36,7 @@ jobs:
     machine:
       image: ubuntu-2004:current
     environment:
-      IMAGE_NAME: "croc/unimus"
+      IMAGE_NAME: "accuris-infrastructure/unimus"
     steps:
       - checkout
       - attach_workspace:
@@ -44,8 +44,7 @@ jobs:
       - run:
           name: docker login
           command: |
-            echo $DOCKERHUB_PASS | docker login --username $DOCKERHUB_USER --password-stdin
-            echo $QUAYIO_PASS | docker login --username $QUAYIO_USER --password-stdin quay.io
+            echo $CR_PAT | docker login ghcr.io -u accuris-infrastructure --password-stdin
       - run:
           name: docker build arm64
           command: |
@@ -58,16 +57,15 @@ jobs:
           name: docker image push
           command: |
             docker images
-            docker tag $IMAGE_NAME $IMAGE_NAME:dev || { echo "retag failed"; exit 1; }
-            docker tag $IMAGE_NAME quay.io/$IMAGE_NAME:dev || { echo "retag failed"; exit 1; }
-            docker push $IMAGE_NAME:dev || { echo "push failed"; exit 1; }
-            docker push quay.io/$IMAGE_NAME:dev || { echo "push failed"; exit 1; }
+            docker tag $IMAGE_NAME ghcr.io/$IMAGE_NAME:dev || { echo "retag failed"; exit 1; }
+            docker push ghcr.io/$IMAGE_NAME:dev || { echo "push failed"; exit 1; }
+
   containerbuilder-arm-job:
     machine:
       image: ubuntu-2004:current
     resource_class: arm.medium
     environment:
-      IMAGE_NAME: "croc/unimus-arm64"
+      IMAGE_NAME: "accuris-infrastructure/unimus-arm64"
     steps:
       - checkout
       - attach_workspace:
@@ -75,8 +73,7 @@ jobs:
       - run:
           name: docker login
           command: |
-            echo $DOCKERHUB_PASS | docker login --username $DOCKERHUB_USER --password-stdin
-            echo $QUAYIO_PASS | docker login --username $QUAYIO_USER --password-stdin quay.io
+            echo $CR_PAT | docker login ghcr.io -u accuris-infrastructure --password-stdin
       - run:
           name: docker build arm64
           command: |
@@ -89,10 +86,9 @@ jobs:
           name: docker image push
           command: |
             docker images
-            docker tag $IMAGE_NAME $IMAGE_NAME:dev || { echo "retag failed"; exit 1; }
-            docker tag $IMAGE_NAME quay.io/$IMAGE_NAME:dev || { echo "retag failed"; exit 1; }
-            docker push $IMAGE_NAME:dev || { echo "push failed"; exit 1; }
-            docker push quay.io/$IMAGE_NAME:dev || { echo "push failed"; exit 1; }
+            docker tag $IMAGE_NAME ghcr.io/$IMAGE_NAME:dev || { echo "retag failed"; exit 1; }
+            docker push ghcr.io/$IMAGE_NAME:dev || { echo "push failed"; exit 1; }
+
 # workflows
 workflows:
   myflow:
